# Generated by Django 3.1.5 on 2021-01-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlantName', models.CharField(max_length=200, null=True)),
                ('Condition', models.CharField(max_length=200, null=True)),
                ('DiseaseName', models.CharField(max_length=200, null=True)),
                ('Medicines', models.CharField(max_length=200, null=True)),
                ('Precautions', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
