# Generated by Django 3.1.5 on 2021-03-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypdda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Precautions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
